#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };
	enum BUFFERID{ BUFFER_RCCOL, BUFFER_TERRAIN, BUFFER_CUBEDRA, BUFFER_TEXCUBE,BUFFER_TEXSQUARE,
		BUFFER_TERRAINTEX, BUFFER_LANDTEX, BUFFER_FOREST, BUFFER_RIFT, BUFFER_VOLCANO, BUFFER_ICEAGE, 
		BUFFER_SKYSPHERE, BUFFER_CAVECYLINDER, BUFFER_VENTCUBE, BUFFER_END	};
	enum PARTICLEID { PART_ATK, PART_WIND, PART_END };	//파티클 클래스별 enum
	enum INFO { INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	// DYNAMIC의 경우 매 프레임마다 갱신이 필요한 컴포넌트
	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END};
	enum TEXTURETYPE { TEX_NORMAL, TEX_CUBE, TEX_END };
	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_STENCIL,RENDER_PARTICLE,RENDER_END };

	// 오브젝트풀용 구분 아이디
	enum OBJID { JUMP_MONSTER, STAND_MONSTER, RUN_MONSTER, CHASE_MONSTER, NORMAL_BULLET, OBJ_END };

	// 로딩씬 ID
	enum LOADINGID { LOADING_STAGE, LOADING_BOSS, LOADING_END };

	//Direct Input
	enum MOUSEKEYSTATE {DIM_LB,DIM_RB,DIR_MB,DIM_END};
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };
}


#endif // Engine_Enum_h__
